let hospitalsArray = [
    "Spitalul Clinic Colțea",
    "Spitalul Universitar de Urgență București",
    "Spitalul Clinic Dr. I. Cantacuzino",
    "Spitalul Clinic de Urgență Floreasca",
    "Spitalul Clinic de Urgență Bagdasar-Arseni",
    "Spitalul Clinic de Urgență Bucur",
    "Spitalul Clinic de Urgență Sf. Ioan",
    "Spitalul Clinic de Urgență Sf. Pantelimon",
    "Spitalul Clinic de Urgență Sf. Maria",
    "Spitalul Clinic de Urgență Elias",
    "Spitalul Clinic de Urgență Sf. Spiridon",
    "Spitalul Clinic de Psihiatrie Prof. Dr. Al. Obregia",
    "Spitalul Clinic de Recuperare",
    "Spitalul Clinic de Chirurgie Oro-Maxilo-Facială",
    "Spitalul Clinic de Boli Infecțioase și Tropicale",
    "Spitalul Clinic de Copii Grigore Alexandrescu",
    "Spitalul Clinic de Copii Marie Curie",
    "Spitalul Clinic de Obstetrică-Ginecologie Panait Sârbu",
    "Spitalul Clinic de Pneumoftiziologie Marius Nasta",
    "Spitalul Clinic de Pneumoftiziologie Dr. Victor Babeș",
    "Spitalul Clinic de Pneumologie Leon Daniello",
    "Spitalul Clinic de Boli Infecțioase Dr. Matei Balș",
    "Spitalul Clinic de Nefrologie Dr. Carol Davila",
    "Spitalul Clinic de Urologie Sf. Constantin",
    "Spitalul Clinic de Ortopedie Foisor",
    "Spitalul Clinic de Urgență pentru Copii Grigore Alexandrescu",
    "Spitalul Clinic de Urgență pentru Copii Maria Skłodowska-Curie",
    "Spitalul Clinic de Psihiatrie Prof. Dr. Alexandru Obregia",
    "Spitalul Clinic de Psihiatrie Dr. C.I. Parhon",
    "Spitalul Clinic de Psihiatrie Prof. Dr. Al. Obregia - Secția II",
    "Spitalul Clinic de Urgență Oftalmologică",
    "Spitalul Clinic de Pneumologie Dr. Victor Babeș",
    "Spitalul Clinic de Pneumoftiziologie Marius Nasta - Secția I",
    "Spitalul Clinic de Pneumoftiziologie Marius Nasta - Secția II",
    "Spitalul Clinic de Pneumologie Sf. Luca",
    "Spitalul Clinic de Recuperare Sf. Pantelimon",
    "Spitalul Clinic de Urgență pentru Copii M. S. Curie",
    "Spitalul Clinic de Urgență pentru Copii Marie Curie - Secția II",
    "Spitalul Clinic de Urgență pentru Copii Marie Curie - Secția III",

];

let specialitiesArray = [
    "Anestezie și terapie intensivă",
    "Alergologie și imunologie clinică",
    "Anatomie patologică",
    "Cardiologie",
    "Chirurgie cardiovasculară",
    "Chirurgie generală",
    "Chirurgie orală și maxilo-facială",
    "Chirurgie pediatrică",
    "Chirurgie plastică și microchirurgie reconstructivă",
    "Chirurgie toracică",
    "Dermatologie și venerologie",
    "Diabet, nutriție și boli metabolice",
    "Endocrinologie",
    "Epidemiologie",
    "Gastroenterologie și hepatologie",
    "Genetică medicală",
    "Geriatrie și gerontologie",
    "Hematologie",
    "Imagistică medicală",
    "Medicina de familie",
    "Medicina de laborator",
    "Medicina de urgență",
    "Medicina fizică și de reabilitare",
    "Medicina internă",
    "Medicina legală",
    "Medicina nucleară",
    "Medicina sportivă",
    "Nefrologie",
    "Neurochirurgie",
    "Neurologie",
    "Obstetrică și ginecologie",
    "Oftalmologie",
    "Oncologie medicală",
    "Ortopedie și traumatologie",
    "Otorinolaringologie",
    "Pediatrie",
    "Pneumologie",
    "Psihiatrie",
    "Radiologie și imagistică medicală",
    "Reumatologie",
    "Urologie"
];

module.exports.hospitalsArray = hospitalsArray;
module.exports.specialitiesArray = specialitiesArray;